apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# This automatically applies these labels to all resources and selectors
commonLabels:
  app: spring-cloud-petclinic-service
