apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic-hpoc-1
  namespace: flux-system
spec:
  interval: 5m
  path: "./projects/kubernetes/cl-01" # Points to this folder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # The name of your Git source in Flux
  
  # This section replaces ${APP_HOST} in the base manifests
  postBuild:
    substitute:
      APP_HOST: "petclinic.default.teleflora-workload-cl01.buildit.services"
