- op: replace
  path: /spec/rules/0/host
  value: petclinic.default.teleflora-workload-cl01.buildit.services
- op: replace
  path: /spec/tls/0/hosts/0
  value: petclinic.default.teleflora-workload-cl01.buildit.services
