apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-cloud-petclinic-service
spec:
  tls:
    - hosts:
        - petclinic.default.teleflora-workload-cl01.buildit.services
  rules:
    - host: petclinic.default.teleflora-workload-cl01.buildit.services
