apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../flux-base

patchesStrategicMerge:
  - ingress-patch.yaml
    target:
      kind: Ingress
      name: spring-cloud-petclinic-service
